
language: android

# Use the Travis Container-Based Infrastructure
sudo: false

jdk:
  - oraclejdk8

env:
  global:
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ADB_INSTALL_TIMEOUT=20 # install timeout in minutes (2 minutes by default)
  matrix:
    - ANDROID_TARGET=android-28 ANDROID_ABI=google_apis/armeabi-v7a

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install new Android SDK tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - $ANDROID_TARGET

    # Support library
    - extra-android-support
    - extra-android-m2repository

    # System images
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
    
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_script:
  - chmod +x ./gradlew
  # Emulator Management: Create, Start and Wait
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator

script:
  - ./gradlew clean
  - ./gradlew check # Local unit tests
  - ./gradlew connectedCheck # Instrumented unit tests
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
